# Generated by Django 5.0.6 on 2026-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
    ]
