# Generated by Django 5.0.6 on 2026-04-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Nomi')),
                ('time', models.CharField(blank=True, default='', max_length=20, verbose_name='Vaqt (10:00–12:00)')),
                ('pri', models.CharField(choices=[('danger', 'Muhim'), ('amber', "O'rta"), ('gray', 'Past')], default='gray', max_length=10, verbose_name='Muhimlik')),
                ('cat', models.CharField(default='Boshqa', max_length=100, verbose_name='Kategoriya')),
                ('date', models.CharField(blank=True, default='', max_length=10, verbose_name='Sana (YYYY-MM-DD)')),
                ('done', models.BooleanField(default=False, verbose_name='Bajarildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['date', 'time', '-created_at'],
            },
        ),
    ]
