# Generated by Django 5.0.6 on 2026-04-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Harajat')], max_length=10, verbose_name='Turi')),
                ('amt', models.BigIntegerField(verbose_name="Miqdor (so'm)")),
                ('cat', models.CharField(default='Boshqa', max_length=100, verbose_name='Kategoriya')),
                ('date', models.CharField(blank=True, default='', max_length=20, verbose_name='Sana (15 may)')),
                ('iso_date', models.CharField(blank=True, default='', max_length=10, verbose_name='ISO sana (YYYY-MM-DD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
