# Generated by Django 5.0.6 on 2026-04-26 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amt',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Miqdor (so'm)"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='iso_date',
            field=models.DateField(blank=True, null=True, verbose_name='ISO sana'),
        ),
    ]
