# Generated by Django 5.0.6 on 2026-04-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=20, verbose_name='Provider')),
                ('api_key', models.CharField(help_text='OpenAI yoki Anthropic API kaliti', max_length=200, verbose_name='API kalit')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='Masalan: gpt-4o-mini, gpt-4o, claude-3-haiku-20240307', max_length=100, verbose_name='Model nomi')),
                ('system_prompt', models.TextField(default='Sen "Tartib" deb nomlangan O\'zbek tilidagi shaxsiy samaradorlik ilovasi uchun AI maslahatchi yordamchisisan.\nFoydalanuvchilar sening bilan o\'z vazifalari, focus vaqtlari, daromadlari va ish rejalari haqida suhbatlashadilar.\n\nQoidalar:\n1. Har doim O\'zbek tilida javob ber\n2. Qisqa, aniq va amaliy maslahatlar ber\n3. Foydalanuvchi ma\'lumotlariga (vazifalar, focus, daromad) asoslanib javob ber\n4. Do\'stona va rag\'batlantiruvchi tonda gapir\n5. HTML teglari ishlatmaslik, oddiy matn yoz\n6. Javob 3-5 jumladan uzun bo\'lmasin', help_text='AI ning xulq-atvori va vazifasini belgilovchi prompt', verbose_name='System prompt')),
                ('max_tokens', models.PositiveIntegerField(default=500, help_text='Javobning maksimal uzunligi', verbose_name='Maksimal tokenlar')),
                ('temperature', models.FloatField(default=0.7, help_text='0 = aniq, 1 = kreativ, 2 = tasodifiy', verbose_name='Harorat (0.0-2.0)')),
                ('is_active', models.BooleanField(default=True, help_text='Bu sozlamani ishlatish', verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Sozlamalar',
                'verbose_name_plural': 'AI Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI')], max_length=10)),
                ('content', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Chat tarixi',
                'verbose_name_plural': 'Chat tarixi',
                'ordering': ['created_at'],
            },
        ),
    ]
