# Generated by Django 5.0.6 on 2026-04-26 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='max_tokens',
            field=models.PositiveIntegerField(default=500, help_text='50 dan 4096 gacha', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4096)], verbose_name='Maksimal tokenlar'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini (tekin)'), ('ollama', 'Ollama (mahalliy, bepul)'), ('offline', 'AI siz (mahalliy algoritm)')], default='openai', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='0 = aniq, 1 = kreativ, 2 = tasodifiy', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Harorat (0.0-2.0)'),
        ),
    ]
