# Generated by Django 5.0.6 on 2026-04-26 06:20

from django.db import migrations
from apps.ai_chat.models import EncryptedField


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_alter_aisettings_max_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='api_key',
            field=EncryptedField(
                help_text='OpenAI yoki Anthropic API kaliti (shifrlangan holda saqlanadi)',
                max_length=500,
                verbose_name='API kalit'
            ),
        ),
    ]
